/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pcr' at '2/13/18 1:21 PM' with Gradle 2.14.1
 *
 * @author pcr, @date 2/13/18 1:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
